### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jo3rn** [jo3rn/blockchAIn#4]
I played with the chain in the `main` method.
Unfortunately I get an error. But I don't know why.
Here is my code:
```java
public class HorstlChain {
  /* ... */
  public static void main(String[] args) {
    ExamAttendance genesisExamAttendance = ExamAttendance.getRandomAttendance();
    HorstlChain chain = new HorstlChain(genesisExamAttendance);
    chain.addBlock(ExamAttendance.getRandomAttendance());
    chain.corruptChain();
  }
}
```

And this is the error I get:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 100
	at HorstlChain.corruptChain(HorstlChain.java:67)
	at HorstlChain.main(HorstlChain.java:17)
```

What is happening here? I think it has something to do with the `corruptChain()` method... How to fix this?

**Comment by nicolafan** [comment]
Hi @jo3rn, in the `corruptChain()` method you initialize the local integer `blockToCorrupt` to the value `currentIndex - 2` while the private attribute `currentIndex` is initialized as `0` in the class. Then since `blockToCurrupt` will be equal to `-2`, when it's used as an index it will throw an `ArrayIndexOutOfBoundsException`. You should initialize `blockToCorrupt` to the value `currentIndex` or `currentIndex` to `2`.

**Comment by jo3rn** [comment]
Hey @nicolafan, good to see that you have tracked down the culprit. This issue serves as a learning example for a Java course at the University of Applied Sciences Fulda, so I will not correct the error for now. Of course you can still contribute a pull request with a solution. Ideally in such a way that `corruptChain` also works with a chain length < 4.

One remark:
When calling `corruptChain` the value of `currentIndex` is `1`, because it is updated in the `addBlock` method. This means `blockToCorrupt` is equal to `-1`. That the error message nevertheless speaks of an index of -2 is due to [this line](https://github.com/jo3rn/blockchAIn/blob/174353f766aab709a0d06f8c7c2c45af17f807a7/de/jo3rn/horstlchain/HorstlChain.java#L79):
```java
horstlChain[blockToCorrupt - 1].getHash());
```

**Comment by nicolafan** [comment]
Hi @jo3rn I'm sorry for the incovenience 🙂. I'm deleting my answer. Thank you for your answer!
